//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ravi_MscIT_WebAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbFoodWebApiEntities : DbContext
    {
        public dbFoodWebApiEntities()
            : base("name=dbFoodWebApiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLFoodOrder> TBLFoodOrders { get; set; }
        public virtual DbSet<TBLRole> TBLRoles { get; set; }
        public virtual DbSet<TBLUser> TBLUsers { get; set; }
    }
}
