//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ravi_MscIT_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLFoodOrder
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Cuisine { get; set; }
        public decimal Price { get; set; }
        public int Quantity { get; set; }
    }
}
