//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ravi_MscIT_WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLUser
    {
        public int Uid { get; set; }
        public string Name { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public int Role_fk { get; set; }
    
        public virtual TBLRole TBLRole { get; set; }
    }
}
